# Representación del mapa del metro
metro_map = {
    'Auditorio': ['Periferico Norte'],
    'Periferico Norte': ['Auditorio', 'Dermatologico'],
    'Dermatologico': ['Periferico Norte', 'Atemajac'],
    'Atemajac': ['Dermatologico', 'Division del Norte'],
    'Division del Norte': ['Atemajac', 'Avila Camacho'],
    'Avila Camacho': ['Division del Norte', 'Circunvalacion Country', 'Normal', 'Mezquitan'],
    'Mezquitan': ['Avila Camacho', 'Refugio'],
    'Refugio': ['Mezquitan', 'Juarez'],
    'Juarez': ['Refugio', 'Plaza Universidad', 'Mexicaltzingo'],
    'Mexicaltzingo': ['Juarez', 'Washington'],
    'Washington': ['Mexicaltzingo', 'Santa Filomena'],
    'Santa Filomena': ['Washington', 'Unidad Deportiva'],
    'Unidad Deportiva': ['Santa Filomena', 'Urdaneta'],
    'Urdaneta': ['Unidad Deportiva', '18 de Marzo'],
    '18 de Marzo': ['Urdaneta', 'Isla Raza'],
    'Isla Raza': ['18 de Marzo', 'Patria Sur'],
    'Patria Sur': ['Isla Raza', 'España'],
    'España': ['Patria Sur', 'Tesoro'],
    'Tesoro': ['España', 'Periferico Sur'],
    'Periferico Sur': ['Tesoro'],
    'Plaza Universidad': ['Juarez', 'Santuario', 'Independencia', 'San Juan de Dios'],
    'San Juan de Dios': ['Plaza Universidad', 'Belisario Dominguez'],
    'Belisario Dominguez': ['San Juan de Dios', 'Oblatos'],
    'Oblatos': ['Belisario Dominguez', 'Cristobal de Oñate'],
    'Cristobal de Oñate': ['Oblatos', 'San Andres'],
    'San Andres': ['Cristobal de Oñate', 'San Jacinto'],
    'San Jacinto': ['San Andres', 'La Aurora'],
    'La Aurora': ['San Jacinto', 'Tetlan'],
    'Tetlan': ['La Aurora'],
    'Arcos de Zapopan': ['Periferico Belenes'],
    'Periferico Belenes': ['Arcos de Zapopan', 'Mercado del Mar'],
    'Mercado del Mar': ['Periferico Belenes', 'Zapopan Centro'],
    'Zapopan Centro': ['Mercado del Mar', 'Plaza Patria'],
    'Plaza Patria': ['Zapopan Centro', 'Circunvalacion Country'],
    'Circunvalacion Country': ['Plaza Patria', 'Avila Camacho'],
    'Normal': ['Avila Camacho', 'Santuario'],
    'Santuario': ['Normal', 'Plaza Universidad'],
    'Independencia': ['Plaza Universidad', 'Plaza de la Bandera'],
    'Plaza de la Bandera': ['Independencia', 'CUCEI'],
    'CUCEI': ['Plaza de la Bandera', 'Revolucion'],
    'Revolucion': ['CUCEI', 'Rio Nilo'],
    'Rio Nilo': ['Revolucion', 'Tlaquepaque Centro'],
    'Tlaquepaque Centro': ['Rio Nilo', 'Lazaro Cardenas'],
    'Lazaro Cardenas': ['Tlaquepaque Centro', 'Central de Autobuses'],
    'Central de Autobuses': ['Lazaro Cardenas'],
}

# Tiempos estimados entre estaciones (en minutos)
tiempos_estimados = {
    ('Auditorio', 'Periferico Norte'): 3,
    ('Periferico Norte', 'Auditorio'): 3,
    ('Periferico Norte', 'Dermatologico'): 3,
    ('Dermatologico', 'Periferico Norte'): 3,
    ('Dermatologico', 'Atemajac'): 3,
    ('Atemajac', 'Dermatologico'): 3,
    ('Atemajac', 'Division del Norte'): 3,
    ('Division del Norte', 'Atemajac'): 3,
    ('Division del Norte', 'Avila Camacho'): 3,
    ('Avila Camacho', 'Division del Norte'): 3,
    ('Avila Camacho', 'Circunvalacion Country'): 4,
    ('Avila Camacho', 'Normal'): 4,
    ('Avila Camacho', 'Mezquitan'): 4,
    ('Circunvalacion Country', 'Avila Camacho'): 4,
    ('Normal', 'Avila Camacho'): 4,
    ('Mezquitan', 'Avila Camacho'): 4,
    ('Mezquitan', 'Refugio'): 3,
    ('Refugio', 'Mezquitan'): 3,
    ('Refugio', 'Juarez'): 3,
    ('Juarez', 'Refugio'): 3,
    ('Juarez', 'Plaza Universidad'): 3,
    ('Juarez', 'Mexicaltzingo'): 3,
    ('Mexicaltzingo', 'Juarez'): 3,
    ('Mexicaltzingo', 'Washington'): 3,
    ('Washington', 'Mexicaltzingo'): 3,
    ('Washington', 'Santa Filomena'): 3,
    ('Santa Filomena', 'Washington'): 3,
    ('Santa Filomena', 'Unidad Deportiva'): 3,
    ('Unidad Deportiva', 'Santa Filomena'): 3,
    ('Unidad Deportiva', 'Urdaneta'): 3,
    ('Urdaneta', 'Unidad Deportiva'): 3,
    ('Urdaneta', '18 de Marzo'): 3,
    ('18 de Marzo', 'Urdaneta'): 3,
    ('18 de Marzo', 'Isla Raza'): 3,
    ('Isla Raza', '18 de Marzo'): 3,
    ('Isla Raza', 'Patria Sur'): 3,
    ('Patria Sur', 'Isla Raza'): 3,
    ('Patria Sur', 'España'): 3,
    ('España', 'Patria Sur'): 3,
    ('España', 'Tesoro'): 3,
    ('Tesoro', 'España'): 3,
    ('Tesoro', 'Periferico Sur'): 3,
    ('Periferico Sur', 'Tesoro'): 3,
    ('Plaza Universidad', 'Juarez'): 3,
    ('Plaza Universidad', 'Santuario'): 4,
    ('Plaza Universidad', 'Independencia'): 4,
    ('Plaza Universidad', 'San Juan de Dios'): 4,
    ('San Juan de Dios', 'Plaza Universidad'): 4,
    ('San Juan de Dios', 'Belisario Dominguez'): 4,
    ('Belisario Dominguez', 'San Juan de Dios'): 4,
    ('Belisario Dominguez', 'Oblatos'): 4,
    ('Oblatos', 'Belisario Dominguez'): 4,
    ('Oblatos', 'Cristobal de Oñate'): 4,
    ('Cristobal de Oñate', 'Oblatos'): 4,
    ('Cristobal de Oñate', 'San Andres'): 4,
    ('San Andres', 'Cristobal de Oñate'): 4,
    ('San Andres', 'San Jacinto'): 4,
    ('San Jacinto', 'San Andres'): 4,
    ('San Jacinto', 'La Aurora'): 4,
    ('La Aurora', 'San Jacinto'): 4,
    ('La Aurora', 'Tetlan'): 4,
    ('Tetlan', 'La Aurora'): 4,
    ('Arcos de Zapopan', 'Periferico Belenes'): 4,
    ('Periferico Belenes', 'Arcos de Zapopan'): 4,
    ('Periferico Belenes', 'Mercado del Mar'): 4,
    ('Mercado del Mar', 'Periferico Belenes'): 4,
    ('Mercado del Mar', 'Zapopan Centro'): 4,
    ('Zapopan Centro', 'Mercado del Mar'): 4,
    ('Zapopan Centro', 'Plaza Patria'): 4,
    ('Plaza Patria', 'Zapopan Centro'): 4,
    ('Plaza Patria', 'Circunvalacion Country'): 4,
    ('Circunvalacion Country', 'Plaza Patria'): 4,
    ('Circunvalacion Country', 'Avila Camacho'): 4,
    ('Normal', 'Avila Camacho'): 4,
    ('Santuario', 'Normal'): 4,
    ('Santuario', 'Plaza Universidad'): 4,
    ('Independencia', 'Plaza Universidad'): 4,
    ('Independencia', 'Plaza de la Bandera'): 4,
    ('Plaza de la Bandera', 'Independencia'): 4,
    ('Plaza de la Bandera', 'CUCEI'): 4,
    ('CUCEI', 'Plaza de la Bandera'): 4,
    ('CUCEI', 'Revolucion'): 4,
    ('Revolucion', 'CUCEI'): 4,
    ('Revolucion', 'Rio Nilo'): 4,
    ('Rio Nilo', 'Revolucion'): 4,
    ('Rio Nilo', 'Tlaquepaque Centro'): 4,
    ('Tlaquepaque Centro', 'Rio Nilo'): 4,
    ('Tlaquepaque Centro', 'Lazaro Cardenas'): 4,
    ('Lazaro Cardenas', 'Tlaquepaque Centro'): 4,
    ('Lazaro Cardenas', 'Central de Autobuses'): 4,
    ('Central de Autobuses', 'Lazaro Cardenas'): 4,
}

# Estaciones servidas por cada ruta
estaciones_por_ruta = {
    'Ruta1': ['Auditorio', 'Periferico Norte', 'Dermatologico', 'Atemajac', 'Division del norte', 'Ávila Camacho', 'Mezquitán', 'Refugio', 'Juárez', 'Mexicaltzingo', 'Washington', 'Santa Filomena', 'Unidad deportiva', 'Urdaneta', '18 de Marzo', 'Isla Raza', 'Patria Sur', 'España', 'Tesoro', 'Periferico Sur'],
    'Ruta2': ['Juárez', 'Plaza Universidad', 'San Juan de Dios', 'Belisario Dominguez', 'Oblatos', 'Cristobal de Oñante', 'San Andrés', 'San Jacinto', 'La Aurora', 'Tetlán'],
    'Ruta3': ['Arcos de Zapopan', 'Periférico Belenés', 'Mercado del Mar', 'Zapopan Centro', 'Plaza Patria', 'Circunvalación Country', 'Ávila Camacho', 'Normal', 'Santuario', 'Plaza Universidad', 'Independencia', 'Plaza de la bandera', 'CUCEI', 'Revolución', 'Rio Nilo', 'Tlaquepaque Centro', 'Lázaro Cárdenas', 'Central de Autobuses'],
}